name: frontend
description: "SSAFY 자율프로젝트 C207"
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.0.1
  # recommend_screen
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0

  # for gallery image
  image_picker: ^1.1.0

  # for http request
  dio: ^5.4.3+1

  # for nation flag
  flag: ^7.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter